﻿// ============================================
// NatureSurvi - Base de données Produits
// ============================================

const PRODUCTS = [
  {
    id: 1,
    name: "Lampe frontale LED rechargeable Velamp",
    category: "Éclairage",
    price: 15, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/prod2.jpg",
    description: "Lampe frontale LED rechargeable et réglable Velamp. Idéale pour la randonnée, le camping et les situations d'urgence. Légère, robuste, bandeau réglable confortable.",
    badges: ["Bestseller","Essentiel"],
    rating: 4.8,
    reviews: 312,
    shipping: "Livraison 2-3 jours",
    variants: [
      { label: "350 lm — 5W", price: 20, stripeLink: "https://buy.stripe.com/4gMfZ94YHgAFanx4jIcfM2W" },
      { label: "400 lm — 6W", price: 24, stripeLink: "https://buy.stripe.com/28E9AL76PachfHR3fEcfM2X" }
    ],
  },
  {
    id: 3,
    name: "Lanterne frontale MIL-TEC tactique olive",
    category: "Éclairage",
    price: 20, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/prod3.jpg",
    description: "Lanterne LED frontale MIL-TEC, coloris olive militaire. Robuste et fiable pour le camping, la chasse et les activités outdoor. Légère et pratique.",
    badges: ["Essentiel"],
    rating: 4.5,
    reviews: 156,
    shipping: "Livraison 2-3 jours",
    stripeLink: "https://buy.stripe.com/28E6ozdvd3NTbrBeYmcfM2Y",
  },
  {
    id: 4,
    name: "Lanterne frontale Nebo Einstein 250lm",
    category: "Éclairage",
    price: 20, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/prod4.jpg",
    description: "Lanterne LED frontale Nebo Einstein 250 lumens. Compacte et puissante pour la randonnée et le camping. Plusieurs modes d'éclairage.",
    badges: ["Nouveau"],
    rating: 4.4,
    reviews: 89,
    shipping: "Livraison 2-3 jours",
    stripeLink: "https://buy.stripe.com/cNi8wH76PgAF7blaI6cfM2Z",
  },
  {
    id: 5,
    name: "Couteau Opinel acier inoxydable",
    category: "Outils",
    price: 11, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/prod5.jpg",
    description: "L'iconique couteau Opinel, fabriqué en France. Lame acier inoxydable, manche en bois de hêtre, virole tournante de sécurité. Indispensable en randonnée et bushcraft. Disponible en plusieurs tailles.",
    badges: ["Bestseller"],
    rating: 4.8,
    reviews: 445,
    shipping: "Livraison 2-3 jours",
    variants: [
      { label: "N°8 — 8,5 cm inox", price: 14, stripeLink: "https://buy.stripe.com/eVq00b3UDfwB3Z9bMacfM30" },
      { label: "N°9 — 9 cm carbone", price: 20, stripeLink: "https://buy.stripe.com/5kQcMXezhbgleDN3fEcfM31" },
      { label: "N°10 — 10 cm inox", price: 20, stripeLink: "https://buy.stripe.com/3cI8wH0Ir849dzJ5nMcfM32" }
    ],
  },
  {
    id: 8,
    name: "Pelle pliable de camping",
    category: "Outils",
    price: 14, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/prod8.jpg",
    description: "Pelle pliable compacte et robuste pour le camping, la survie et le jardinage. Se range facilement dans un sac à dos. Indispensable en bivouac. Disponible en 2 modèles.",
    badges: ["Essentiel"],
    rating: 4.5,
    reviews: 178,
    shipping: "Livraison 2-3 jours",
    variants: [
      { label: "Pelle noire métal", price: 20, stripeLink: "https://buy.stripe.com/aFa00b2Qz0BH3Z98zYcfM33" },
      { label: "Cellfast Ideal Pro", price: 20, stripeLink: "https://buy.stripe.com/4gMeV59eXgAF3Z92bAcfM34" }
    ],
  },
  {
    id: 9,
    name: "Tente de camping Bestway",
    category: "Survie",
    price: 26, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/prod9.jpg",
    description: "Tente de camping Bestway en polyester fibre de verre. Facile à monter, imperméable, résistante. Idéale pour le camping estival et les festivals. Disponible en 2, 3 ou 4 personnes.",
    rating: 4.4,
    reviews: 112,
    shipping: "Livraison 3-5 jours",
    variants: [
      { label: "2 personnes — 205×145 cm", price: 30, stripeLink: "https://buy.stripe.com/00w6ozcr9fwB3Z92bAcfM35" }
    ],
  },
  {
    id: 14,
    name: "Réchaud à gaz Open Norte camping",
    category: "Survie",
    price: 40, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/prod14.jpg",
    description: "Réchaud à gaz Open Norte compact et puissant. Idéal pour le camping et la randonnée. Allumage piézo intégré, régulateur de flamme précis. Robuste et fiable.",
    badges: ["Bestseller"],
    rating: 4.6,
    reviews: 189,
    shipping: "Livraison 2-3 jours",
    stripeLink: "https://buy.stripe.com/cNi4gr0Ir5W1gLVaI6cfM36",
  },
  {
    id: 15,
    name: "Lampe frontale Black Diamond Spot 400",
    category: "Éclairage",
    price: 40, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/prod15.jpg",
    description: "Lampe frontale Black Diamond Spot 400 lumens, rechargeable. Étanche IPX8, autonomie jusqu'à 200h. La référence des alpinistes et randonneurs exigeants.",
    badges: ["Bestseller","Essentiel"],
    rating: 4.8,
    reviews: 312,
    shipping: "Livraison 2-3 jours",
    stripeLink: "https://buy.stripe.com/8x2fZ9ezhbglanxeYmcfM37",
  },
  {
    id: 16,
    name: "Lanterne LED Brennenstuhl frontale 200lm",
    category: "Éclairage",
    price: 30, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/prod16.jpg",
    description: "Lanterne frontale LED Brennenstuhl 1178780, 200 lumens. Marque allemande reconnue pour sa fiabilité. Légère, réglable, idéale pour le bricolage et l'outdoor.",
    badges: ["Essentiel"],
    rating: 4.5,
    reviews: 145,
    shipping: "Livraison 2-3 jours",
    stripeLink: "https://buy.stripe.com/14A14ffDl70553dg2qcfM38",
  },
  {
    id: 19,
    name: "Lampe frontale Stak LED 10W 1200lm",
    category: "Éclairage",
    price: 50, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/prod19.jpg",
    description: "Lampe frontale Stak 10W ultra-puissante 1200 lumens. Rechargeable USB-C, autonomie longue durée. Pour les sorties nocturnes exigeantes et la spéléologie.",
    badges: ["Nouveau","Essentiel"],
    rating: 4.7,
    reviews: 67,
    shipping: "Livraison 2-3 jours",
    stripeLink: "https://buy.stripe.com/3cI4gr3UDbgl53deYmcfM3a",
  },
  {
    id: 21,
    name: "Sac à dos randonnée Mammut Cargon",
    category: "Sacs à dos",
    price: 80, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/prod22.jpg",
    description: "Sac à dos Mammut Cargon, qualité suisse premium. Grande capacité pour les longues randonnées et expéditions. Tissu robuste, dos ventilé, bretelles ergonomiques. Disponible en 2 tailles.",
    badges: ["Bestseller","Essentiel"],
    rating: 4.8,
    reviews: 78,
    shipping: "Livraison 2-3 jours",
    variants: [
      { label: "40 L — randonnée", price: 100, stripeLink: "https://buy.stripe.com/9B6cMX76P3NTfHReYmcfM3b" }
    ],
  },
  {
    id: 22,
    name: "Sac à dos Mammut Alto 24L",
    category: "Sacs à dos",
    price: 90, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/prod23.jpg",
    description: "Sac à dos Mammut Alto 24L, parfait pour les randonnées à la journée. Format compact mais bien équipé. Marque suisse de référence pour l'outdoor.",
    badges: ["Nouveau"],
    rating: 4.6,
    reviews: 45,
    shipping: "Livraison 2-3 jours",
    stripeLink: "https://buy.stripe.com/9B63cn62L705fHR2bAcfM3c",
  },
  {
    id: 23,
    name: "Sac à dos Reebok Noah polyvalent",
    category: "Sacs à dos",
    price: 30, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/prod27.jpg",
    description: "Sac à dos casual Reebok Noah. Polyvalent pour le sport, l'école ou les sorties en plein air. Compartiments multiples, robuste et confortable.",
    rating: 4.4,
    reviews: 132,
    shipping: "Livraison 2-3 jours",
    stripeLink: "https://buy.stripe.com/6oU00b1Mv7053Z9aI6cfM3d",
  },
  {
    id: 24,
    name: "Chargeur universel Varta piles rechargeables",
    category: "Énergie",
    price: 30, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/prod24.jpg",
    description: "Chargeur de batterie Varta universel. Compatible AA, AAA, C, D et 9V. Indispensable pour économiser et être autonome en piles. Marque allemande de référence.",
    badges: ["Essentiel"],
    rating: 4.7,
    reviews: 234,
    shipping: "Livraison 2-3 jours",
    stripeLink: "https://buy.stripe.com/9B614fezh8498fp9E2cfM3e",
  },
  {
    id: 25,
    name: "Pack piles rechargeables Varta AA + AAA",
    category: "Énergie",
    price: 10, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/prod25.jpg",
    description: "Pack piles rechargeables Varta 1,2V AA et AAA. Économiques et écologiques, rechargeables jusqu'à 1000 fois. Idéal pour lampes torches, télécommandes et appareils outdoor.",
    badges: ["Bestseller"],
    rating: 4.8,
    reviews: 312,
    shipping: "Livraison 2-3 jours",
    stripeLink: "https://buy.stripe.com/eVq00bfDldot53d7vUcfM3f",
  },
  {
    id: 26,
    name: "Piles Duracell Plus Power Boost AAA (12 unités)",
    category: "Énergie",
    price: 10, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/prod26.jpg",
    description: "Pack de 12 piles Duracell Plus Power Boost AAA 1,5V. Longue durée, performance supérieure. Pour vos appareils électroniques outdoor : lampes, GPS, talkies-walkies.",
    badges: ["Essentiel"],
    rating: 4.6,
    reviews: 189,
    shipping: "Livraison 2-3 jours",
    stripeLink: "https://buy.stripe.com/14A4gr4YH705fHR3fEcfM3g",
  },
  {
    id: 29,
    name: "Canne à pêche Kali Kunnan",
    category: "Pêche",
    price: 19, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/prod29.jpg",
    description: "Canne à pêche télescopique Kali Kunnan. Légère et robuste pour la pêche en rivière, lac ou mer. Se range facilement pour le transport. Disponible en 2 longueurs.",
    rating: 4.4,
    reviews: 134,
    shipping: "Livraison 2-3 jours",
    variants: [
      { label: "240 cm — légère", price: 20, stripeLink: "https://buy.stripe.com/dRm00b76P1FL7bl3fEcfM3h" },
      { label: "300 cm — polyvalente", price: 23, stripeLink: "https://buy.stripe.com/00w7sDgHp2JPgLV2bAcfM3i" }
    ],
  },
  {
    id: 31,
    name: "Boîte de rangement pêche Kali Kunnan",
    category: "Pêche",
    price: 12, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/prod31.jpg",
    description: "Boîte de rangement pour accessoires de pêche Kali Kunnan. Compartiments modulables pour hameçons, leurres et plombs. Pratique et résistante pour emporter partout.",
    badges: ["Essentiel"],
    rating: 4.3,
    reviews: 76,
    shipping: "Livraison 2-3 jours",
    stripeLink: "https://buy.stripe.com/8x25kv0Irckpanx17wcfM3j",
  },
  {
    id: 32,
    name: "Caméra de sport 4K Sunstech Adventure",
    category: "Électronique outdoor",
    price: 44, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/prod32.jpg",
    description: "Caméra de sport 4K Sunstech Adventure. Filmez vos aventures en haute définition. Résistante aux chocs, idéale pour le vélo, la randonnée, le kayak. Légère et compacte.",
    badges: ["Nouveau"],
    rating: 4.3,
    reviews: 67,
    shipping: "Livraison 2-3 jours",
    stripeLink: "https://buy.stripe.com/9B6eV5cr9gAF0MXg2qcfM3k",
  },
  {
    id: 33,
    name: "Caméra de sport SK8 Elite outdoor",
    category: "Électronique outdoor",
    price: 65, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/prod33.jpg",
    description: "Caméra de sport SK8 Elite pour l'outdoor extrême. Résistante à l'eau et aux chocs. Parfaite pour VTT, ski, escalade et plongée. Accessoires de fixation inclus.",
    badges: ["Essentiel"],
    rating: 4.4,
    reviews: 89,
    shipping: "Livraison 2-3 jours",
    stripeLink: "https://buy.stripe.com/cNibITbn598d3Z93fEcfM3l",
  },
  {
    id: 34,
    name: "Bracelet connecté Xiaomi Band outdoor",
    category: "Électronique outdoor",
    price: 70, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/prod34.jpg",
    description: "Bracelet d'activités Xiaomi 1,56\" pour le suivi sportif outdoor. GPS, cardiofréquencemètre, compteur de pas, altimètre. Étanche, autonomie 14 jours. Parfait pour la randonnée.",
    badges: ["Nouveau"],
    rating: 4.6,
    reviews: 134,
    shipping: "Livraison 2-3 jours",
    stripeLink: "https://buy.stripe.com/eVq00bgHpdotdzJeYmcfM3m",
  },
  {
    id: 35,
    name: "Veste outdoor Alphaventure homme",
    category: "Vêtements outdoor",
    price: 14, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/prod35.jpg",
    description: "Veste légère Alphaventure Bidinamarca pour homme, coloris kaki militaire. Coupe-vent, idéale pour la chasse, la randonnée et les activités outdoor. Poches zippées.",
    rating: 4.3,
    reviews: 78,
    shipping: "Livraison 2-3 jours",
    variants: [
      { label: "Légère — kaki", price: 20, stripeLink: "https://buy.stripe.com/14AdR13UDachcvF2bAcfM3n" }
    ],
  },
  {
    id: 37,
    name: "Casque d'escalade Black Diamond",
    category: "Escalade",
    price: 50, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/prod37.jpg",
    description: "Casque d'escalade Black Diamond léger et résistant. Protection optimale pour l'escalade en falaise et en salle. Ventilation efficace, réglage rapide. Norme CE EN12492.",
    badges: ["Essentiel"],
    rating: 4.7,
    reviews: 156,
    shipping: "Livraison 2-3 jours",
    stripeLink: "https://buy.stripe.com/6oUeV5gHp849cvF9E2cfM3o",
  },
  {
    id: 38,
    name: "Harnais d'escalade Kong Sierra Duo",
    category: "Escalade",
    price: 30, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/prod38.jpg",
    description: "Harnais d'escalade Kong Sierra Duo pour débutants. Confortable et sécurisé, adapté à la salle et à la falaise. Réglages rapides, ceinture ventrale renforcée.",
    badges: ["Essentiel"],
    rating: 4.5,
    reviews: 89,
    shipping: "Livraison 2-3 jours",
    stripeLink: "https://buy.stripe.com/3cIfZ90Irbgl3Z93fEcfM3p",
  },
  {
    id: 39,
    name: "Slackline Schildkröt 15m jaune",
    category: "Escalade",
    price: 88, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/prod39.jpg",
    description: "Slackline Schildkröt 15 mètres, couleur jaune vif. Kit complet avec sangle, tendeur et protège-arbre. Idéal pour la pratique en forêt, parc ou jardin. Pour tous niveaux.",
    badges: ["Nouveau"],
    rating: 4.4,
    reviews: 45,
    shipping: "Livraison 3-5 jours",
    stripeLink: "https://buy.stripe.com/4gM00bfDl4RX67hcQecfM3q",
  },
  {
    id: 40,
    name: "Pain croustillant randonnée Trek'n Eat",
    category: "Alimentation outdoor",
    price: 10, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/prod40.jpg",
    description: "Pain croustillant déshydraté Trek'n Eat 500g. Léger, longue conservation, parfait pour le bivouac et les randonnées multi-jours. Rapide à réhydrater, goût naturel.",
    badges: ["Essentiel","Survie"],
    rating: 4.5,
    reviews: 52,
    shipping: "Livraison 2-3 jours",
    stripeLink: "https://buy.stripe.com/4gM14f62L4RXcvFg2qcfM3r",
  },
  {
    id: 42,
    name: "Barre énergétique Naak Ultra Energy caramel",
    category: "Alimentation outdoor",
    price: 5, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/prod42.jpg",
    description: "Barre énergétique Naak Ultra Energy 50g, saveur caramel café. Riche en protéines et glucides complexes. Idéale avant et pendant l'effort outdoor : randonnée, course, cyclisme.",
    badges: ["Nouveau"],
    rating: 4.4,
    reviews: 34,
    shipping: "Livraison 2-3 jours",
    stripeLink: "https://buy.stripe.com/bJe9AL4YH5W12V55nMcfM3t",
  },
  {
    id: 43,
    name: "Sac d'hydratation Joluvi 2,5L",
    category: "Cyclisme & Trail",
    price: 10, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/prod43.jpg",
    description: "Sac d'hydratation Joluvi 2,5L léger et ergonomique. Poche à eau intégrée, tube buveur, sangles réglables. Idéal pour le trail, le VTT et la randonnée rapide.",
    badges: ["Essentiel"],
    rating: 4.4,
    reviews: 89,
    shipping: "Livraison 2-3 jours",
    stripeLink: "https://buy.stripe.com/fZu4gr2Qz7053Z96rQcfM3u",
  },
  {
    id: 44,
    name: "Sacoche de vélo PRO Performance 5,5L",
    category: "Cyclisme & Trail",
    price: 40, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/prod44.jpg",
    description: "Sacoche de vélo PRO Performance 5,5L. Fixation rapide sur guidon ou selle. Imperméable, idéale pour les sorties longue distance. Compatible avec tous types de vélos.",
    badges: ["Nouveau"],
    rating: 4.6,
    reviews: 43,
    shipping: "Livraison 2-3 jours",
    stripeLink: "https://buy.stripe.com/cNiaEPezhach67hdUicfM3v",
  },
  {
    id: 46,
    name: "Montre Casio Diver 100M",
    category: "Montres outdoor",
    price: 58, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/prod46.jpg",
    description: "Montre Casio Diver 100M, boîtier 44,5mm. Étanche jusqu'à 100 mètres. Idéale pour la plongée, la natation et les activités aquatiques. Robuste et fiable.",
    badges: ["Essentiel"],
    rating: 4.6,
    reviews: 178,
    shipping: "Livraison 2-3 jours",
    stripeLink: "https://buy.stripe.com/cNi00b8aT0BHdzJdUicfM3w",
  },
  {
    id: 48,
    name: "Plat lyophilisé Trek'n Eat hamburger",
    category: "Alimentation outdoor",
    price: 11, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/prod48.jpg",
    description: "Plat lyophilisé Trek'n Eat hamburgers. Repas complet pour le bivouac et la randonnée. Facile à préparer : ajoutez juste de l'eau chaude. Goût savoureux, haute valeur nutritive.",
    badges: ["Bestseller"],
    rating: 4.5,
    reviews: 89,
    shipping: "Livraison 2-3 jours",
    stripeLink: "https://buy.stripe.com/00w7sD0Ir849anx9E2cfM3x",
  },
  {
    id: 49,
    name: "Dessert lyophilisé Trek'n Eat chocolat",
    category: "Alimentation outdoor",
    price: 9, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/prod49.jpg",
    description: "Dessert lyophilisé Trek'n Eat au chocolat 100g. Le petit plaisir sucré du bivouac. Léger, longue conservation, préparation ultra-rapide à l'eau chaude.",
    badges: ["Nouveau"],
    rating: 4.4,
    reviews: 56,
    shipping: "Livraison 2-3 jours",
    stripeLink: "https://buy.stripe.com/14A5kv8aT7059jtbMacfM3y",
  },
  {
    id: 51,
    name: "Gourde randonnée outdoor",
    category: "Cyclisme & Trail",
    price: 10, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/prod51.jpg",
    description: "Gourde Regatta 1L légère et résistante. Bouchon à vis étanche, graduation intérieure. Indispensable pour la randonnée, le camping et le sport en plein air.",
    badges: ["Essentiel"],
    rating: 4.4,
    reviews: 145,
    shipping: "Livraison 2-3 jours",
    variants: [
      { label: "1L — Regatta noire", price: 12, stripeLink: "https://buy.stripe.com/cNifZ9ezhach0MX03scfM3A" }
    ],
  },
  {
    id: 60,
    name: "Bracelet paracord survie 7 en 1",
    category: "Outils",
    price: 7, 
    supplier: "CJdropshipping",
    image: "img/prod_paracord.jpg",
    description: "Bracelet de survie paracord 7 en 1 : corde 3m, firestarter, sifflet, boussole, couteau, grattoir, lampe LED. Indispensable en randonnée et survie. Réglable.",
    badges: ["Bestseller","Essentiel"],
    rating: 4.6,
    reviews: 412,
    shipping: "Livraison 2-3 jours",
    variants: [
      { label: "Noir", price: 7, stripeLink: "https://buy.stripe.com/3cI7sD9eX4RX53d7vUcfM3B" },
      { label: "Vert militaire", price: 7, stripeLink: "https://buy.stripe.com/eVq28j8aTachfHRcQecfM3C" },
      { label: "Kaki", price: 7, stripeLink: "https://buy.stripe.com/aFafZ90Irbgl2V56rQcfM3D" },
      { label: "Orange fluo", price: 7, stripeLink: "https://buy.stripe.com/6oU4gr62L0BH67heYmcfM3E" },
      { label: "Camouflage", price: 7, stripeLink: "https://buy.stripe.com/cNicMXaj10BH9jtbMacfM3F" }
    ],
  },
  {
    id: 61,
    name: "Briquet de survie ferrocérium",
    category: "Outils",
    price: 5, 
    supplier: "CJdropshipping",
    image: "img/prod_firestarter.jpg",
    description: "Allume-feu en ferrocérium avec grattoir en acier inoxydable. Produit jusqu'à 3000°C d'étincelles. Fonctionne par tous les temps, même mouillé. Indispensable pour survivre en forêt.",
    badges: ["Bestseller","Essentiel"],
    rating: 4.7,
    reviews: 528,
    shipping: "Livraison 2-3 jours",
    variants: [
      { label: "Standard 10cm", price: 5, stripeLink: "https://buy.stripe.com/aFadR176P2JPeDN03scfM3G" },
      { label: "Large 12cm — durée x3", price: 7, stripeLink: "https://buy.stripe.com/eVq6oz76PbglcvFbMacfM3H" },
      { label: "XL 15cm + cordage", price: 10, stripeLink: "https://buy.stripe.com/fZuaEP9eXckpdzJ3fEcfM3I" }
    ],
  },
  {
    id: 62,
    name: "Couverture de survie isotherme",
    category: "Survie",
    price: 3, 
    supplier: "CJdropshipping",
    image: "img/prod_couverture.jpg",
    description: "Couverture de survie isotherme dorée/argentée. Réfléchit 90% de la chaleur corporelle. Légère (55g), compacte, imperméable. Essentielle en kit 72h et premiers secours.",
    badges: ["Bestseller","Essentiel"],
    rating: 4.7,
    reviews: 654,
    shipping: "Livraison 2-3 jours",
    variants: [
      { label: "×1 — Individuelle", price: 3, stripeLink: "https://buy.stripe.com/00w5kvfDlgAF8fp03scfM3J" },
      { label: "×4 — Pack famille", price: 10, stripeLink: "https://buy.stripe.com/8x25kv1MvdotdzJ5nMcfM3K" }
    ],
  },
  {
    id: 63,
    name: "Sifflet de survie 120 dB",
    category: "Outils",
    price: 2, 
    supplier: "CJdropshipping",
    image: "img/prod_sifflet.jpg",
    description: "Sifflet de survie ultra-puissant 120 dB, audible à 1 km. Sans bille (fonctionne mouillé), clip de ceinture inclus. Indispensable en randonnée, escalade et urgences.",
    badges: ["Essentiel"],
    rating: 4.6,
    reviews: 298,
    shipping: "Livraison 2-3 jours",
    variants: [
      { label: "Orange — 120 dB", price: 2, stripeLink: "https://buy.stripe.com/8x27sD4YH3NT1R14jIcfM3L" },
      { label: "Noir — 120 dB", price: 2, stripeLink: "https://buy.stripe.com/cNi6oz4YHgAF2V5cQecfM3M" },
      { label: "3-en-1 boussole+sifflet+thermomètre", price: 5, stripeLink: "https://buy.stripe.com/cNi00b76Pach8fp6rQcfM3N" }
    ],
  },
  {
    id: 64,
    name: "Couteau de survie multifonction",
    category: "Outils",
    price: 20, 
    supplier: "CJdropshipping",
    image: "img/prod_couteau_survie.jpg",
    description: "Couteau de survie lame fixe en acier inox 440, manche ergonomique. Inclus : pierre à affûter, allume-feu, sifflet, étui cordura. Polyvalent pour la chasse, le bushcraft et l'outdoor.",
    badges: ["Bestseller"],
    rating: 4.5,
    reviews: 187,
    shipping: "Livraison 2-3 jours",
    variants: [
      { label: "Lame 15cm — noir", price: 20, stripeLink: "https://buy.stripe.com/3cI7sD76PdotgLV3fEcfM3O" },
      { label: "Lame 20cm + hachette", price: 22, stripeLink: "https://buy.stripe.com/fZudR1bn5fwBanxcQecfM3P" },
      { label: "Machette 35cm", price: 25, stripeLink: "https://buy.stripe.com/cNi00bcr93NTeDNg2qcfM3Q" }
    ],
  },
  {
    id: 65,
    name: "Kit de survie 72h complet",
    category: "Survie",
    price: 30, 
    supplier: "CJdropshipping",
    image: "img/prod_kit72h.jpg",
    description: "Kit de survie 72h tout-en-un : couverture isotherme, allume-feu, sifflet, corde paracord 5m, filtre eau, boussole, couteau pliant, rations énergie. Idéal famille ou individuel.",
    badges: ["Bestseller","Essentiel"],
    rating: 4.7,
    reviews: 389,
    shipping: "Livraison 3-5 jours",
    variants: [
      { label: "Kit individuel — 12 pièces", price: 30, stripeLink: "https://buy.stripe.com/eVq6oz4YHdot2V56rQcfM3R" },
      { label: "Kit famille 4 — 24 pièces", price: 35, stripeLink: "https://buy.stripe.com/4gMcMXcr9849eDN8zYcfM3S" },
      { label: "Kit pro — 32 pièces premium", price: 40, stripeLink: "https://buy.stripe.com/9B63cn1Mvesx9jtcQecfM3T" }
    ],
  },
  {
    id: 66,
    name: "Filtre à eau portable survie",
    category: "Survie",
    price: 20, 
    supplier: "CJdropshipping",
    image: "img/prod_filtre_eau.jpg",
    description: "Filtre à eau portable de survie — élimine 99,9999% des bactéries et parasites. Débit 1L/min, filtre jusqu'à 100 000 litres. Léger 57g, compatible toutes gourdes. Certifié survie.",
    badges: ["Essentiel","Bestseller"],
    rating: 4.8,
    reviews: 456,
    shipping: "Livraison 2-3 jours",
    variants: [
      { label: "Filtre paille individuel", price: 20, stripeLink: "https://buy.stripe.com/14A00bfDl705gLV17wcfM3U" },
      { label: "Filtre bouteille 0.5L", price: 22, stripeLink: "https://buy.stripe.com/28EeV58aT98d1R15nMcfM3V" },
      { label: "Kit complet paille+bouteille+pastilles", price: 25, stripeLink: "https://buy.stripe.com/5kQ5kvaj1gAF7bl8zYcfM3W" }
    ],
  },
  {
    id: 67,
    name: "Talkies-walkies longue portée",
    category: "Électronique outdoor",
    price: 40, 
    supplier: "CJdropshipping",
    image: "img/prod_talkie.jpg",
    description: "Talkies-walkies longue portée 5 km (terrain dégagé). 16 canaux, résistant à l'eau IPX4, VOX, lampe LED intégrée. Idéal camping, randonnée et situations d'urgence. Vendu par paire.",
    badges: ["Nouveau","Essentiel"],
    rating: 4.4,
    reviews: 213,
    shipping: "Livraison 3-5 jours",
    variants: [
      { label: "Paire 5km — noir", price: 40, stripeLink: "https://buy.stripe.com/28EdR19eX4RX1R1g2qcfM3X" },
      { label: "Paire 8km — orange", price: 42, stripeLink: "https://buy.stripe.com/8x29ALgHp4RX0MXeYmcfM3Y" },
      { label: "Pack ×4 — famille", price: 48, stripeLink: "https://buy.stripe.com/7sYfZ9gHpesx3Z93fEcfM3Z" }
    ],
  },
  {
    id: 68,
    name: "Corde paracord 550 militaire",
    category: "Outils",
    price: 7, 
    supplier: "CJdropshipping",
    image: "img/prod_paracord_corde.jpg",
    description: "Corde paracord 550 de type III militaire. 7 fils intérieurs, résistance 249 kg. Polyvalente : abri, filet, attaches, bracelet, lasso. Indispensable en survival et bushcraft.",
    badges: ["Bestseller"],
    rating: 4.7,
    reviews: 312,
    shipping: "Livraison 2-3 jours",
    variants: [
      { label: "10m — Noir", price: 7, stripeLink: "https://buy.stripe.com/6oUaEP8aTgAFbrB3fEcfM40" },
      { label: "10m — Vert militaire", price: 7, stripeLink: "https://buy.stripe.com/aFa14f2QzachfHReYmcfM41" },
      { label: "10m — Camouflage", price: 7, stripeLink: "https://buy.stripe.com/3cIeV562LgAFgLV03scfM42" },
      { label: "30m — Noir", price: 10, stripeLink: "https://buy.stripe.com/aFa7sD2Qz5W153d03scfM43" },
      { label: "50m — Noir", price: 20, stripeLink: "https://buy.stripe.com/4gM6oz0Ir8492V56rQcfM44" }
    ],
  },
  {
    id: 69,
    name: "Boussole militaire de précision",
    category: "Outils",
    price: 15, 
    supplier: "CJdropshipping",
    image: "img/prod_boussole.jpg",
    description: "Boussole militaire de précision lensatique avec miroir de visée. Degrés et mils, phosphorescent, boîtier métal résistant. Idéale pour la randonnée, la chasse et la navigation en forêt.",
    badges: ["Essentiel"],
    rating: 4.6,
    reviews: 178,
    shipping: "Livraison 2-3 jours",
    variants: [
      { label: "Boussole simple", price: 15, stripeLink: "https://buy.stripe.com/fZu7sDezhesx1R1aI6cfM45" },
      { label: "Boussole + miroir de visée", price: 17, stripeLink: "https://buy.stripe.com/14AfZ9cr95W1cvF6rQcfM46" },
      { label: "Kit navigation : boussole+carte+sifflet", price: 20, stripeLink: "https://buy.stripe.com/14AfZ9dvdgAFeDN03scfM47" }
    ],
  },
  {
    id: 70,
    name: "Lampe torche tactique LED",
    category: "Éclairage",
    price: 20, 
    supplier: "CJdropshipping",
    image: "img/prod_torche.jpg",
    description: "Lampe torche tactique LED ultra-puissante rechargeable USB-C. 5 modes : max/mi/bas/stroboscope/SOS. Résistante IPX6, zoom ajustable, aluminium militaire. Parfaite pour la survie.",
    badges: ["Bestseller","Essentiel"],
    rating: 4.7,
    reviews: 534,
    shipping: "Livraison 2-3 jours",
    variants: [
      { label: "1000 lm — Noire", price: 20, stripeLink: "https://buy.stripe.com/fZudR1dvdgAFgLVbMacfN00" },
      { label: "2000 lm — Noire", price: 23, stripeLink: "https://buy.stripe.com/00w00bgHp3NTeDNdUicfN01" },
      { label: "2000 lm — Camouflage", price: 23, stripeLink: "https://buy.stripe.com/00waEPbn5esxbrBbMacfN02" },
      { label: "5000 lm — Pro", price: 27, stripeLink: "https://buy.stripe.com/00w8wHdvd1FL7bl3fEcfN03" }
    ],
  },
  {
    id: 71,
    name: "Sac de survie Bug Out Bag",
    category: "Sacs à dos",
    price: 45, 
    supplier: "CJdropshipping",
    image: "img/prod_bugout.jpg",
    description: "Sac de survie Bug Out Bag 40L militaire. Structure MOLLE, résistant à l'eau, multi-compartiments. Idéal pour un kit 72h complet. Disponible en 3 coloris tactiques.",
    badges: ["Nouveau","Essentiel"],
    rating: 4.5,
    reviews: 167,
    shipping: "Livraison 3-5 jours",
    variants: [
      { label: "40L — Noir", price: 45, stripeLink: "https://buy.stripe.com/4gM8wHfDl5W153d6rQcfN04" },
      { label: "40L — Vert militaire", price: 45, stripeLink: "https://buy.stripe.com/00w7sD9eXfwB7blcQecfN05" },
      { label: "40L — Camouflage", price: 45, stripeLink: "https://buy.stripe.com/00w00bcr93NT8fp9E2cfN06" },
      { label: "60L — Noir expédition", price: 55, stripeLink: "https://buy.stripe.com/6oUfZ94YH4RX1R13fEcfN07" }
    ],
  },
  {
    id: 80,
    name: "Gants de jardinage résistants aux épines",
    category: "Outils de jardin",
    price: 7, 
    supplier: "CJdropshipping",
    image: "img/jard_gants.jpg",
    description: "Gants de jardinage résistants aux épines et coupures. Cuir de vachette sur la paume, manchette longue anti-égratignures. Parfaits pour rosiers, ronces, travaux intensifs.",
    badges: ["Bestseller"],
    rating: 4.6,
    reviews: 312,
    shipping: "Livraison 2-3 jours",
    variants: [
      { label: "S — Kaki", price: 7, stripeLink: "https://buy.stripe.com/6oUcMX0Iresx7bl6rQcfN08" },
      { label: "M — Kaki", price: 7, stripeLink: "https://buy.stripe.com/5kQ7sDdvd8491R13fEcfN09" },
      { label: "L — Kaki", price: 7, stripeLink: "https://buy.stripe.com/28E9ALdvdbgl9jt8zYcfN0a" },
      { label: "XL — Kaki", price: 7, stripeLink: "https://buy.stripe.com/dRmbITgHp3NTcvFeYmcfN0b" },
      { label: "M — Rose", price: 7, stripeLink: "https://buy.stripe.com/5kQ4gr76PckpfHR3fEcfN0c" },
      { label: "L — Rose", price: 7, stripeLink: "https://buy.stripe.com/4gM3cnbn5dotanx5nMcfN0d" }
    ],
  },
  {
    id: 81,
    name: "Arrosoir en acier galvanisé",
    category: "Outils de jardin",
    price: 23, 
    supplier: "CJdropshipping",
    image: "img/jard_arrosoir.jpg",
    description: "Arrosoir classique en acier galvanisé, pomme amovible pour arrosage fin. Résistant à la rouille, équilibré et ergonomique. Idéal pour potager, fleurs et plantes en pot.",
    badges: ["Nouveau"],
    rating: 4.5,
    reviews: 145,
    shipping: "Livraison 2-3 jours",
    variants: [
      { label: "5L — Vert", price: 23, stripeLink: "https://buy.stripe.com/bJe14fcr93NTcvF03scfN0e" },
      { label: "8L — Vert", price: 25, stripeLink: "https://buy.stripe.com/14AbITaj13NTbrBeYmcfN0f" },
      { label: "10L — Vert", price: 27, stripeLink: "https://buy.stripe.com/5kQeV51Mv8499jt03scfN0g" },
      { label: "5L — Rouge", price: 23, stripeLink: "https://buy.stripe.com/eVq7sDezhbgl2V59E2cfN0h" }
    ],
  },
  {
    id: 82,
    name: "Serre de jardin tunnel modulable",
    category: "Serres & Abris",
    price: 45, 
    supplier: "CJdropshipping",
    image: "img/jard_serre.jpg",
    description: "Serre tunnel de jardin en polyéthylène renforcé, armature acier galvanisé. Protège les plantes du gel et des intempéries. Montage facile sans outils. Ventilation zippée.",
    badges: ["Bestseller","Essentiel"],
    rating: 4.5,
    reviews: 234,
    shipping: "Livraison 3-5 jours",
    variants: [
      { label: "Petite — 100×50×80 cm", price: 45, stripeLink: "https://buy.stripe.com/3cI4grcr9bgl0MX2bAcfN0i" },
      { label: "Moyenne — 180×60×90 cm", price: 48, stripeLink: "https://buy.stripe.com/dRm3cn9eX849dzJ3fEcfN0j" },
      { label: "Grande — 240×120×200 cm", price: 55, stripeLink: "https://buy.stripe.com/6oU5kvgHpbglanxeYmcfN0k" },
      { label: "XL — 300×150×200 cm", price: 70, stripeLink: "https://buy.stripe.com/3cI14fbn53NTdzJcQecfN0l" }
    ],
  },
  {
    id: 83,
    name: "Tuteurs pour plantes et tomates",
    category: "Outils de jardin",
    price: 7, 
    supplier: "CJdropshipping",
    image: "img/jard_tuteurs.jpg",
    description: "Tuteurs en bambou ou métal pour tomates, haricots et plantes grimpantes. Résistants aux intempéries, réutilisables saison après saison. Pack de 10 ou 20 pièces.",
    badges: ["Essentiel"],
    rating: 4.4,
    reviews: 198,
    shipping: "Livraison 2-3 jours",
    variants: [
      { label: "×10 bambou 90cm", price: 7, stripeLink: "https://buy.stripe.com/eVqaEPfDl98d8fpg2qcfN0m" },
      { label: "×20 bambou 90cm", price: 8, stripeLink: "https://buy.stripe.com/7sY28j4YH0BH7blbMacfN0n" },
      { label: "×10 métal 120cm", price: 10, stripeLink: "https://buy.stripe.com/14A8wHgHp705anxg2qcfN0o" },
      { label: "×20 métal 120cm", price: 14, stripeLink: "https://buy.stripe.com/dRm9AL2Qz1FL67hbMacfN0p" },
      { label: "×5 spirale tomates 150cm", price: 10, stripeLink: "https://buy.stripe.com/dRm28jfDl98d7bl17wcfN0q" }
    ],
  },
  {
    id: 84,
    name: "Terreau universel potager bio",
    category: "Terre & Amendements",
    price: 10, 
    supplier: "CJdropshipping",
    image: "img/jard_terreau.jpg",
    description: "Terreau universel enrichi en compost bio pour potager, semis et rempotage. Texture aérée favorisant le développement racinaire. Sans tourbe. Enrichi en éléments nutritifs naturels.",
    badges: ["Nouveau","Essentiel"],
    rating: 4.6,
    reviews: 312,
    shipping: "Livraison 3-5 jours",
    variants: [
      { label: "5L — semis et boutures", price: 10, stripeLink: "https://buy.stripe.com/7sY7sDbn5705anx17wcfN0r" },
      { label: "20L — potager", price: 12, stripeLink: "https://buy.stripe.com/6oU5kvfDlfwB2V53fEcfN0s" },
      { label: "50L — grand jardin", price: 24, stripeLink: "https://buy.stripe.com/8x24grgHpgAFgLV9E2cfN0t" }
    ],
  },
  {
    id: 85,
    name: "Kit semences potager 20 légumes",
    category: "Semences & Graines",
    price: 13, 
    supplier: "CJdropshipping",
    image: "img/jard_semences.jpg",
    description: "Kit de 20 sachets de semences de légumes bio — tomates, courgettes, haricots, carottes, salades, radis, poivrons. Non traitées, reproductibles. Idéal pour démarrer un potager complet.",
    badges: ["Bestseller","Essentiel"],
    rating: 4.7,
    reviews: 456,
    shipping: "Livraison 2-3 jours",
    variants: [
      { label: "Kit 10 légumes essentiels", price: 13, stripeLink: "https://buy.stripe.com/8x25kv3UD3NTdzJeYmcfN0u" },
      { label: "Kit 20 légumes complet", price: 14, stripeLink: "https://buy.stripe.com/14A9AL62LbglcvF5nMcfN0v" },
      { label: "Kit 30 légumes + herbes", price: 16, stripeLink: "https://buy.stripe.com/bJebITaj15W1eDN2bAcfN0w" },
      { label: "Kit 50 variétés premium", price: 20, stripeLink: "https://buy.stripe.com/aFa28j62L1FL8fp3fEcfN0x" }
    ],
  },
  {
    id: 86,
    name: "Composteur de jardin 300L",
    category: "Composteurs",
    price: 40, 
    supplier: "CJdropshipping",
    image: "img/jard_composteur.jpg",
    description: "Composteur de jardin en plastique recyclé 300L. Trappe de récupération en bas, couvercle anti-pluie, aérations latérales. Transformez vos déchets en engrais naturel en 3 mois.",
    badges: ["Bestseller"],
    rating: 4.5,
    reviews: 198,
    shipping: "Livraison 3-5 jours",
    variants: [
      { label: "300L — Noir", price: 40, stripeLink: "https://buy.stripe.com/dRm28j0Irdot1R103scfN0y" },
      { label: "400L — Noir", price: 43, stripeLink: "https://buy.stripe.com/00w5kv1Mvbgl2V59E2cfN0z" },
      { label: "600L — Noir", price: 50, stripeLink: "https://buy.stripe.com/28EaEP4YH98dcvF6rQcfN0A" }
    ],
  },
  {
    id: 87,
    name: "Kit irrigation goutte à goutte 30 plantes",
    category: "Irrigation",
    price: 20, 
    supplier: "CJdropshipping",
    image: "img/jard_irrigation.jpg",
    description: "Kit d'irrigation goutte à goutte automatique pour 30 plantes. Tuyaux PE flexible, goutteurs réglables, connecteurs étanches. Compatible timer. Économise 70% d'eau par rapport à l'arrosoir.",
    badges: ["Nouveau","Essentiel"],
    rating: 4.6,
    reviews: 234,
    shipping: "Livraison 2-3 jours",
    variants: [
      { label: "Kit 15 plantes", price: 20, stripeLink: "https://buy.stripe.com/bJe7sD76Pbgl0MXaI6cfN0B" },
      { label: "Kit 30 plantes", price: 22, stripeLink: "https://buy.stripe.com/28E8wH8aT0BH1R1eYmcfN0C" },
      { label: "Kit 50 plantes + timer", price: 25, stripeLink: "https://buy.stripe.com/3cI6ozfDl1FLfHR5nMcfN0D" },
      { label: "Kit 100 plantes pro", price: 30, stripeLink: "https://buy.stripe.com/fZu8wHfDl2JP9jteYmcfN0E" }
    ],
  },
  {
    id: 88,
    name: "Pots géotextiles pour potager",
    category: "Bacs & Pots",
    price: 11, 
    supplier: "CJdropshipping",
    image: "img/jard_pots.jpg",
    description: "Pots géotextiles respirants pour potager hors-sol et balcon. Favorisent l'air-pruning des racines et un drainage parfait. Pliables, réutilisables, résistants aux UV. Idéals pour tomates et fraises.",
    badges: ["Nouveau"],
    rating: 4.5,
    reviews: 189,
    shipping: "Livraison 2-3 jours",
    variants: [
      { label: "×5 — 10L Noir", price: 11, stripeLink: "https://buy.stripe.com/eVqbITfDlgAF9jt7vUcfN0F" },
      { label: "×5 — 20L Noir", price: 13, stripeLink: "https://buy.stripe.com/fZubITgHp0BH3Z9aI6cfN0G" },
      { label: "×5 — 30L Noir", price: 14, stripeLink: "https://buy.stripe.com/3cI4gr4YHdot7blaI6cfN0H" },
      { label: "×5 — 10L Vert", price: 11, stripeLink: "https://buy.stripe.com/28E8wHfDlckp7bl2bAcfN0I" },
      { label: "×5 — 20L Vert", price: 13, stripeLink: "https://buy.stripe.com/5kQ00b2QzgAF7blg2qcfN0J" },
      { label: "×10 — 10L Noir — lot", price: 14, stripeLink: "https://buy.stripe.com/bJe9AL0Ir84967hdUicfN0K" }
    ],
  },
  {
    id: 89,
    name: "Programmateur d'arrosage automatique",
    category: "Irrigation",
    price: 22, 
    supplier: "CJdropshipping",
    image: "img/jard_timer.jpg",
    description: "Programmateur d'arrosage automatique digital. Jusqu'à 6 programmes par jour, durée 1 min à 24h. Résistant IPX5, raccord universel 3/4\". Économise eau et temps au jardin.",
    badges: ["Bestseller","Essentiel"],
    rating: 4.5,
    reviews: 267,
    shipping: "Livraison 2-3 jours",
    variants: [
      { label: "Timer simple — 1 zone", price: 22, stripeLink: "https://buy.stripe.com/5kQ5kvcr94RXbrBaI6cfN0L" },
      { label: "Timer double — 2 zones", price: 35, stripeLink: "https://buy.stripe.com/8x200b9eXdotbrB03scfN0M" },
      { label: "Timer WiFi — app smartphone", price: 49, stripeLink: "https://buy.stripe.com/eVq14f8aT7058fp5nMcfN0N" }
    ],
  },
  {
    id: 90,
    name: "Station d'énergie portable 300Wh",
    category: "Énergie",
    price: 189, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.cjdropshipping.com",
    image: "img/station_300wh.jpg",
    description: "Station LiFePO4 300Wh. Sortie AC 220V + USB-C 60W + DC 12V. Recharge solaire, voiture ou secteur. Silencieuse. Idéale coupures, camping, van.",
    badges: ["Nouveau","Essentiel"],
    rating: 4.7,
    reviews: 0,
    shipping: "Livraison 5-7 jours",
    variants: [
      { label: "300Wh — AC+USB-C+DC", price: 189, stripeLink: "https://buy.stripe.com/cNi28j76P1FL8fp8zYcfN0O" },
      { label: "500Wh — version pro", price: 299, stripeLink: "https://buy.stripe.com/8x26oz76P0BHbrB03scfN0P" }
    ],
  },
  {
    id: 91,
    name: "Panneau solaire pliable 100W monocristallin",
    category: "Énergie",
    price: 79, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.cjdropshipping.com",
    image: "img/panneau_100w.jpg",
    description: "Panneau solaire pliable 100W monocristallin. Efficacité 23%, ETFE, USB-A+USB-C+MC4. IPX4. Compatible toutes stations portables.",
    badges: ["Nouveau"],
    rating: 4.6,
    reviews: 0,
    shipping: "Livraison 5-7 jours",
    variants: [
      { label: "100W — 2 panneaux", price: 79, stripeLink: "https://buy.stripe.com/dRmeV50Irbgl67h2bAcfN0Q" },
      { label: "200W — 4 panneaux", price: 139, stripeLink: "https://buy.stripe.com/8x25kvcr9bgl1R15nMcfN0R" }
    ],
  },
  {
    id: 92,
    name: "Kit solaire 200W + station 300Wh",
    category: "Énergie",
    price: 249, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.cjdropshipping.com",
    image: "img/kit_solaire_200w.jpg",
    description: "Kit solaire complet : panneau 200W + station portative 300Wh LiFePO4. Recharge en 2-3h de soleil. Zéro installation.",
    badges: ["Nouveau","Essentiel"],
    rating: 4.8,
    reviews: 0,
    shipping: "Livraison 5-7 jours",
    variants: [
      { label: "Kit 200W + 300Wh", price: 249, stripeLink: "https://buy.stripe.com/6oUaEPbn5achbrBbMacfN0S" }
    ],
  },
  {
    id: 93,
    name: "Chargeur solaire USB pliable 21W",
    category: "Énergie",
    price: 32, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.cjdropshipping.com",
    image: "img/chargeur_solaire_21w.jpg",
    description: "Chargeur solaire pliable 21W. 2× USB-A + USB-C. Efficacité 22%. 380g. Pour smartphones, GPS et lampes.",
    rating: 4.5,
    reviews: 0,
    shipping: "Livraison 3-5 jours",
    variants: [
      { label: "21W — 3 panneaux", price: 32, stripeLink: "https://buy.stripe.com/dRm8wHbn53NTbrB8zYcfN0T" },
      { label: "40W — 4 panneaux", price: 52, stripeLink: "https://buy.stripe.com/14A5kv9eXach53dcQecfN0U" }
    ],
  },
  {
    id: 94,
    name: "Batterie solaire de secours 20000mAh",
    category: "Énergie",
    price: 28, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.cjdropshipping.com",
    image: "img/batterie_solaire_20000.jpg",
    description: "Batterie solaire 20000mAh panneau 5W intégré, IP66, lampe SOS LED. Charge 5 smartphones. Idéale randonnée et urgence.",
    rating: 4.5,
    reviews: 0,
    shipping: "Livraison 3-5 jours",
    variants: [
      { label: "20000mAh — noir IP66", price: 28, stripeLink: "https://buy.stripe.com/5kQfZ9cr9ach53d7vUcfN0V" }
    ],
  },
  {
    id: 95,
    name: "Lampe solaire outdoor 2000 lm",
    category: "Énergie",
    price: 22, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.cjdropshipping.com",
    image: "img/lampe_solaire_2000.jpg",
    description: "Lampe solaire outdoor 2000 lm. LFP 6000mAh. IP65. Autonomie 8-12h. Détecteur mouvement. Pour jardin, terrasse, camping.",
    badges: ["Nouveau"],
    rating: 4.5,
    reviews: 0,
    shipping: "Livraison 3-5 jours",
    variants: [
      { label: "2000 lm + détecteur mouvement", price: 22, stripeLink: "https://buy.stripe.com/7sY3cnaj15W17bl9E2cfN0W" }
    ],
  },
  {
    id: 96,
    name: "Contrôleur de charge solaire MPPT 30A",
    category: "Énergie",
    price: 25, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.cjdropshipping.com",
    image: "img/controleur_mppt.jpg",
    description: "Régulateur MPPT 30A. 12V/24V. LCD. Jusqu'à 400W de panneaux. Protection intégrée. Pour chalet, camping-car, bateau.",
    badges: ["Nouveau"],
    rating: 4.4,
    reviews: 0,
    shipping: "Livraison 3-5 jours",
    variants: [
      { label: "MPPT 30A — 12V/24V", price: 25, stripeLink: "https://buy.stripe.com/14A00b1Mv98deDN3fEcfN0X" },
      { label: "MPPT 60A — 12/24/48V + Bluetooth", price: 49, stripeLink: "https://buy.stripe.com/9B64gr9eXckpbrB8zYcfN0Y" }
    ],
  }
];

// ============================================
// Produits Jardinage (IDs 101-136)
// ============================================
const PRODUCTS_JARDINAGE = [
  {
    id: 101,
    name: "Set d'outils de jardinage 3 pièces",
    category: "Jardinage",
    price: 23, 
    supplier: "CJdropshipping",
    image: "images/jardinage/outils_set.jpg",
    description: "Truelle, transplantoir et cultivateur. Manches ergonomiques antidérapants. Acier inoxydable.",
    badges: ["Essentiel"],
    rating: 4.5,
    reviews: 89,
    shipping: "Livraison 3-5 jours",
    stripeLink: "https://buy.stripe.com/7sY14f3UDdot9jt4jIcfM2m",
  },
  {
    id: 102,
    name: "Bêche de jardin professionnelle",
    category: "Jardinage",
    price: 30, 
    supplier: "CJdropshipping",
    image: "images/jardinage/beche.jpg",
    description: "Lame acier trempé, manche en bois de frêne 120cm. Idéale pour retourner la terre et creuser.",
    badges: ["Essentiel"],
    rating: 4.6,
    reviews: 67,
    shipping: "Livraison 3-5 jours",
    stripeLink: "https://buy.stripe.com/7sY6ozbn5705brBg2qcfM2n",
  },
  {
    id: 103,
    name: "Sécateur professionnel à lame franche",
    category: "Jardinage",
    price: 22, 
    supplier: "CJdropshipping",
    image: "images/jardinage/secateur.jpg",
    description: "Lame en acier SK5 trempé, poignée ergonomique. Coupe nette jusqu'à 25mm de diamètre.",
    badges: ["Bio"],
    rating: 4.7,
    reviews: 145,
    shipping: "Livraison 2-3 jours",
    stripeLink: "https://buy.stripe.com/7sY9AL9eX0BH2V54jIcfM2o",
  },
  {
    id: 104,
    name: "Serre de balcon 4 étagères",
    category: "Jardinage",
    price: 36, 
    supplier: "CJdropshipping",
    image: "images/jardinage/serre_balcon.jpg",
    description: "Structure acier + housse PE transparente. 143x73x61cm. Parfaite pour balcon ou terrasse.",
    badges: ["Nouveau"],
    rating: 4.4,
    reviews: 112,
    shipping: "Livraison 3-5 jours",
    stripeLink: "https://buy.stripe.com/cNi5kv4YHckpgLVg2qcfM2p",
  },
  {
    id: 105,
    name: "Mini serre tunnel de jardin 6m²",
    category: "Jardinage",
    price: 59, 
    supplier: "CJdropshipping",
    image: "images/jardinage/serre_tunnel.jpg",
    description: "Armature galvanisée, bâche 180 microns UV. 300x200x200cm. Protège contre le gel et les insectes.",
    rating: 4.3,
    reviews: 78,
    shipping: "Livraison 5-7 jours",
    stripeLink: "https://buy.stripe.com/aFafZ90Irdot8fpcQecfM2q",
  },
  {
    id: 106,
    name: "Composteur de jardin 300L",
    category: "Jardinage",
    price: 47, 
    supplier: "CJdropshipping",
    image: "images/jardinage/composteur.jpg",
    description: "Plastique recyclé 100%, trappe de récupération en bas. Transforme vos déchets en engrais naturel.",
    badges: ["Bio"],
    rating: 4.5,
    reviews: 134,
    shipping: "Livraison 5-7 jours",
    stripeLink: "https://buy.stripe.com/8x2dR1aj1fwB3Z94jIcfM2r",
  },
  {
    id: 107,
    name: "Lombricomposteur 3 niveaux",
    category: "Jardinage",
    price: 44, 
    supplier: "CJdropshipping",
    image: "images/jardinage/lombri.jpg",
    description: "Compostage aux vers de terre. Produit un engrais liquide ultra-concentré. Idéal appartement.",
    badges: ["Bio","Nouveau"],
    rating: 4.4,
    reviews: 56,
    shipping: "Livraison 3-5 jours",
    stripeLink: "https://buy.stripe.com/28E6ozaj11FL1R1aI6cfM2s",
  },
  {
    id: 108,
    name: "Arrosoir 10L bec long en zinc",
    category: "Jardinage",
    price: 27, 
    supplier: "CJdropshipping",
    image: "images/jardinage/arrosoir.jpg",
    description: "Zinc galvanisé anticorrosion, bec long pour atteindre le pied des plantes. Contenance 10 litres.",
    rating: 4.5,
    reviews: 98,
    shipping: "Livraison 3-5 jours",
    stripeLink: "https://buy.stripe.com/4gMfZ92Qz0BH53daI6cfM2t",
  },
  {
    id: 109,
    name: "Kit goutte-à-goutte 50 plantes",
    category: "Jardinage",
    price: 32, 
    supplier: "CJdropshipping",
    image: "images/jardinage/goutte.jpg",
    description: "Système d'irrigation automatique. 15m de tuyau, 50 goutteurs réglables. Économise 70% d'eau.",
    badges: ["Essentiel"],
    rating: 4.6,
    reviews: 203,
    shipping: "Livraison 2-3 jours",
    stripeLink: "https://buy.stripe.com/cNifZ98aT705cvFbMacfM2u",
  },
  {
    id: 110,
    name: "Carré potager surélevé en bois 120x60cm",
    category: "Jardinage",
    price: 50, 
    supplier: "CJdropshipping",
    image: "images/jardinage/carre_potager.jpg",
    description: "Bois de pin traité autoclave. Hauteur 30cm. Idéal terrasse, balcon ou jardin. Montage facile.",
    badges: ["Essentiel"],
    rating: 4.5,
    reviews: 167,
    shipping: "Livraison 5-7 jours",
    stripeLink: "https://buy.stripe.com/6oUdR162L705brBbMacfM2v",
  },
  {
    id: 111,
    name: "Tour à fraises & plantes aromatiques",
    category: "Jardinage",
    price: 22, 
    supplier: "CJdropshipping",
    image: "images/jardinage/tour_fraises.jpg",
    description: "5 poches de plantation empilables. Culture verticale, gain de place. Parfait pour balcon.",
    badges: ["Nouveau"],
    rating: 4.3,
    reviews: 44,
    shipping: "Livraison 2-3 jours",
    stripeLink: "https://buy.stripe.com/14A5kvdvd8490MXg2qcfM2w",
  },
  {
    id: 112,
    name: "Filet anti-insectes 2x5m",
    category: "Jardinage",
    price: 19, 
    supplier: "CJdropshipping",
    image: "images/jardinage/filet.jpg",
    description: "Maille fine 0,8mm, protège légumes et fruits des insectes et oiseaux. Laisse passer lumière et pluie.",
    badges: ["Bio"],
    rating: 4.4,
    reviews: 88,
    shipping: "Livraison 2-3 jours",
    stripeLink: "https://buy.stripe.com/4gM7sDaj1705eDN3fEcfM2x",
  },
  {
    id: 113,
    name: "Voile d'hivernage 30g/m² - 10x2m",
    category: "Jardinage",
    price: 17, 
    supplier: "CJdropshipping",
    image: "images/jardinage/voile.jpg",
    description: "Protège vos cultures jusqu'à -6°C. Perméable à l'eau et à la lumière. Réutilisable plusieurs saisons.",
    badges: ["Essentiel"],
    rating: 4.5,
    reviews: 121,
    shipping: "Livraison 2-3 jours",
    stripeLink: "https://buy.stripe.com/cNi9AL62L2JP53d8zYcfM2y",
  },
  {
    id: 114,
    name: "Débroussailleuse électrique filaire 600W",
    category: "Jardinage",
    price: 52, 
    supplier: "CJdropshipping",
    image: "images/jardinage2/debroussailleuse_filaire.jpg",
    description: "Tête de coupe rotative, fil nylon ø1,6mm, poignée ergonomique. Légère (~2,5 kg), câble 10m inclus.",
    rating: 4.3,
    reviews: 67,
    shipping: "Livraison 3-5 jours",
    stripeLink: "https://buy.stripe.com/14AaEPezhckpdzJ4jIcfM2z",
  },
  {
    id: 115,
    name: "Débroussailleuse sans fil batterie 20V",
    category: "Jardinage",
    price: 79, 
    supplier: "CJdropshipping",
    image: "images/jardinage2/debroussailleuse_batterie.jpg",
    description: "Li-Ion 20V, tête à double fil, autonomie ~35 min, 2,8 kg. Démarrage instantané, rechargeable en 1h.",
    badges: ["Nouveau"],
    rating: 4.4,
    reviews: 53,
    shipping: "Livraison 3-5 jours",
    stripeLink: "https://buy.stripe.com/3cI00b62L0BH7bl8zYcfM2A",
  },
  {
    id: 116,
    name: "Taille-haie électrique 450W 45cm",
    category: "Jardinage",
    price: 47, 
    supplier: "CJdropshipping",
    image: "images/jardinage2/taillehaie.jpg",
    description: "Lame double action 45cm, espacement dents 16mm, poignée rotative 180°. Léger (2,2 kg).",
    rating: 4.4,
    reviews: 78,
    shipping: "Livraison 3-5 jours",
    stripeLink: "https://buy.stripe.com/8x23cn4YHesxfHR4jIcfM2B",
  },
  {
    id: 117,
    name: "Souffleur-aspirateur de feuilles 3-en-1 2800W",
    category: "Jardinage",
    price: 42, 
    supplier: "CJdropshipping",
    image: "images/jardinage2/souffleur.jpg",
    description: "Souffle, aspire et broie. Sac collecteur 45L, vitesse d'air 290 km/h. Rapport broyage 10:1.",
    rating: 4.3,
    reviews: 45,
    shipping: "Livraison 3-5 jours",
    stripeLink: "https://buy.stripe.com/5kQ4grezh7050MX8zYcfM2C",
  },
  {
    id: 118,
    name: "Tondeuse à gazon électrique 1400W 32cm",
    category: "Jardinage",
    price: 91, 
    supplier: "CJdropshipping",
    image: "images/jardinage2/tondeuse.jpg",
    description: "Largeur de coupe 32cm, 5 hauteurs (25-70mm), bac 30L. Idéale jusqu'à 200 m². Légère (8 kg).",
    badges: ["Bestseller"],
    rating: 4.5,
    reviews: 134,
    shipping: "Livraison 5-7 jours",
    stripeLink: "https://buy.stripe.com/7sY8wH4YH2JPfHR6rQcfM2D",
  },
  {
    id: 119,
    name: "Scarificateur aérateur 2-en-1 1300W 32cm",
    category: "Jardinage",
    price: 69, 
    supplier: "CJdropshipping",
    image: "images/jardinage2/scarificateur.jpg",
    description: "Largeur 32cm, profondeur réglable sur 5 niveaux, bac 30L. Régénère la pelouse, élimine le feutre.",
    rating: 4.4,
    reviews: 56,
    shipping: "Livraison 5-7 jours",
    stripeLink: "https://buy.stripe.com/aFa28j1Mv0BH3Z917wcfM2E",
  },
  {
    id: 120,
    name: "Coupe-bordures électrique 350W",
    category: "Jardinage",
    price: 33, 
    supplier: "CJdropshipping",
    image: "images/jardinage2/coupebordures.jpg",
    description: "Tête pivotante 180°, bobine automatique, manche télescopique. Ultra-léger (1,4 kg).",
    rating: 4.3,
    reviews: 67,
    shipping: "Livraison 3-5 jours",
    stripeLink: "https://buy.stripe.com/4gM6oz76Pesx2V5cQecfM2F",
  },
  {
    id: 121,
    name: "Pulvérisateur à pression 16L sur roues",
    category: "Jardinage",
    price: 39, 
    supplier: "CJdropshipping",
    image: "images/jardinage2/pulverisateur.jpg",
    description: "Chariot à roues, lance télescopique 1,2m, jet continu/brumisation. Grande capacité 16L.",
    rating: 4.4,
    reviews: 89,
    shipping: "Livraison 3-5 jours",
    stripeLink: "https://buy.stripe.com/28E28jaj1achanx4jIcfM2G",
  },
  {
    id: 122,
    name: "Bâche de jardin imperméable 4x6m",
    category: "Jardinage",
    price: 30, 
    supplier: "CJdropshipping",
    image: "images/jardinage2/bache.jpg",
    description: "90g/m², oeillets tous les 50cm, résistante UV. Couvre bois, compost, potager, terrasse.",
    rating: 4.3,
    reviews: 56,
    shipping: "Livraison 3-5 jours",
    stripeLink: "https://buy.stripe.com/dRm6ozezh705brB3fEcfM2H",
  },
  {
    id: 123,
    name: "Brouette pliante en acier galvanisé 100L",
    category: "Jardinage",
    price: 59, 
    supplier: "CJdropshipping",
    image: "images/jardinage2/brouette.jpg",
    description: "Roue pneumatique anti-crevaison, charge max 150 kg. Pliable pour stockage compact. Sans outil.",
    badges: ["Essentiel"],
    rating: 4.5,
    reviews: 112,
    shipping: "Livraison 5-7 jours",
    stripeLink: "https://buy.stripe.com/3cI6ozcr92JP1R1aI6cfM2I",
  },
  {
    id: 124,
    name: "Sécateur Pro Tête Rotative",
    category: "Jardinage",
    price: 7, 
    supplier: "CJdropshipping",
    image: "https://oss-cf.cjdropshipping.com/product/2026/05/11/06/6f6e968a-7d4d-42a6-a31f-ca0c7006a187_trans.jpeg",
    description: "Sécateur à tête rotative pour réduire la fatigue. Lame inox tranchante, ressort anti-retour. Taille précise branches jusqu'à 2 cm.",
    badges: ["Nouveau"],
    rating: 4.5,
    reviews: 34,
    shipping: "Livraison 5-7 jours",
    stripeLink: "https://buy.stripe.com/fZueV50Ir7050MXcQecfM2J",
  },
  {
    id: 125,
    name: "Étagère Plantes Multi-niveaux Style Nordique",
    category: "Jardinage",
    price: 32, 
    supplier: "CJdropshipping",
    image: "https://cf.cjdropshipping.com/quick/product/f4c78289-239f-4259-846f-f2d022ba1255.jpg",
    description: "Présentoir à plantes intérieur 4 niveaux, style scandinave. Idéal pour succulentes, plantes grasses et pothos.",
    badges: ["Nouveau"],
    rating: 4.4,
    reviews: 28,
    shipping: "Livraison 5-7 jours",
    stripeLink: "https://buy.stripe.com/6oU3cn8aTesx53ddUicfM2K",
  },
  {
    id: 126,
    name: "Lampe Solaire Jardin 3 Têtes - Étanche IP65",
    category: "Jardinage",
    price: 32, 
    supplier: "CJdropshipping",
    image: "https://cf.cjdropshipping.com/quick/product/f354d75d-6fcc-4c87-8f37-9b6f24b921a3.jpg",
    description: "Lampe de jardin solaire 3 têtes orientables. Charge automatique le jour, éclairage la nuit. Imperméable IP65.",
    badges: ["Nouveau"],
    rating: 4.5,
    reviews: 42,
    shipping: "Livraison 5-7 jours",
    stripeLink: "https://buy.stripe.com/bJe4gr62L1FLanx5nMcfM2L",
  },
  {
    id: 127,
    name: "Gants de jardinage résistants aux épines",
    category: "Jardinage",
    price: 9, 
    supplier: "CJdropshipping",
    image: "img/jard_gants.jpg",
    description: "Cuir de vachette paume, manchette longue. S / M / L / XL en kaki ou rose.",
    rating: 4.4,
    reviews: 67,
    shipping: "Livraison 2-3 jours",
    stripeLink: "https://buy.stripe.com/3cI3cnfDl84953dg2qcfM2M",
  },
  {
    id: 128,
    name: "Arrosoir en acier galvanisé",
    category: "Jardinage",
    price: 22, 
    supplier: "CJdropshipping",
    image: "img/jard_arrosoir.jpg",
    description: "Pomme amovible, résistant rouille. 5L vert/rouge, 8L, 10L.",
    rating: 4.5,
    reviews: 89,
    shipping: "Livraison 3-5 jours",
    stripeLink: "https://buy.stripe.com/6oUfZ976Pesx7blaI6cfM2N",
  },
  {
    id: 129,
    name: "Serre de jardin tunnel modulable",
    category: "Jardinage",
    price: 39, 
    supplier: "CJdropshipping",
    image: "img/jard_serre.jpg",
    description: "Polyéthylène renforcé, armature acier galvanisé, ventilation zippée. 4 tailles disponibles.",
    rating: 4.3,
    reviews: 56,
    shipping: "Livraison 5-7 jours",
    stripeLink: "https://buy.stripe.com/aFa5kv8aT8493Z96rQcfM2O",
  },
  {
    id: 130,
    name: "Tuteurs pour plantes et tomates",
    category: "Jardinage",
    price: 9, 
    supplier: "CJdropshipping",
    image: "img/jard_tuteurs.jpg",
    description: "Bambou ou métal. ×10/×20 pièces, 90-150cm. Réutilisables.",
    rating: 4.3,
    reviews: 45,
    shipping: "Livraison 2-3 jours",
    stripeLink: "https://buy.stripe.com/9B6aEP9eX84967h03scfM2P",
  },
  {
    id: 131,
    name: "Terreau universel potager bio",
    category: "Jardinage",
    price: 12, 
    supplier: "CJdropshipping",
    image: "img/jard_terreau.jpg",
    description: "Compost bio, sans tourbe, texture aérée. 5L / 20L / 50L.",
    badges: ["Bio"],
    rating: 4.6,
    reviews: 178,
    shipping: "Livraison 3-5 jours",
    stripeLink: "https://buy.stripe.com/8x29ALezhgAF67h03scfM2Q",
  },
  {
    id: 132,
    name: "Kit semences potager 20 légumes",
    category: "Jardinage",
    price: 10, 
    supplier: "CJdropshipping",
    image: "img/jard_semences.jpg",
    description: "Bio, non traitées, reproductibles. De 10 à 50 variétés de légumes.",
    badges: ["Bio","Nouveau"],
    rating: 4.7,
    reviews: 234,
    shipping: "Livraison 2-3 jours",
    stripeLink: "https://buy.stripe.com/4gM28jgHpachfHR17wcfM2R",
  },
  {
    id: 133,
    name: "Composteur de jardin 300L (grande gamme)",
    category: "Jardinage",
    price: 35, 
    supplier: "CJdropshipping",
    image: "img/jard_composteur.jpg",
    description: "Plastique recyclé, trappe récupération, couvercle anti-pluie. 300L / 400L / 600L.",
    badges: ["Bio"],
    rating: 4.5,
    reviews: 134,
    shipping: "Livraison 5-7 jours",
    stripeLink: "https://buy.stripe.com/4gM14fdvd1FL67h17wcfM2S",
  },
  {
    id: 134,
    name: "Kit irrigation goutte à goutte 30 plantes",
    category: "Jardinage",
    price: 12, 
    supplier: "CJdropshipping",
    image: "img/jard_irrigation.jpg",
    description: "Goutteurs réglables, économise 70% d'eau. 15 à 100 plantes.",
    badges: ["Essentiel"],
    rating: 4.6,
    reviews: 189,
    shipping: "Livraison 2-3 jours",
    stripeLink: "https://buy.stripe.com/bJe8wHezh1FL9jt2bAcfM2T",
  },
  {
    id: 135,
    name: "Pots géotextiles pour potager",
    category: "Jardinage",
    price: 12, 
    supplier: "CJdropshipping",
    image: "img/jard_pots.jpg",
    description: "Air-pruning, drainage parfait, UV-résistants. ×5 : 10L / 20L / 30L, noir ou vert.",
    rating: 4.4,
    reviews: 98,
    shipping: "Livraison 2-3 jours",
    stripeLink: "https://buy.stripe.com/8x200b3UDachgLVbMacfM2U",
  },
  {
    id: 136,
    name: "Programmateur d'arrosage automatique",
    category: "Jardinage",
    price: 22, 
    supplier: "CJdropshipping",
    image: "img/jard_timer.jpg",
    description: "6 programmes/jour, IPX5, raccord universel. Version WiFi disponible.",
    badges: ["Nouveau"],
    rating: 4.5,
    reviews: 67,
    shipping: "Livraison 2-3 jours",
    stripeLink: "https://buy.stripe.com/9B67sDezh849eDN3fEcfM2V",
  },
  {
    id: 137,
    name: "Cuve récupération eau de pluie 300L",
    category: "Jardinage",
    price: 59, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/jard_cuve_pluie.jpg",
    description: "Cuve de récupération d'eau de pluie 300 litres en polyéthylène recyclé. Raccord gouttière universel, robinet de soutirage 3/4\", couvercle anti-moustiques. Idéale pour arroser un potager en autonomie. Économisez jusqu'à 50% sur votre consommation d'eau.",
    badges: ["Nouveau","Essentiel"],
    rating: 4.6,
    reviews: 0,
    shipping: "Livraison 5-7 jours",
    variants: [
      { label: "300L — Verte", price: 59, stripeLink: "https://buy.stripe.com/fZu14f8aT849gLVcQecfN0Z" },
      { label: "300L — Noire", price: 59, stripeLink: "https://buy.stripe.com/aFa5kv62L2JPeDN6rQcfN10" },
      { label: "500L — Verte", price: 100, stripeLink: "https://buy.stripe.com/7sY5kv76PachcvFcQecfN11" }
    ],
  },
  {
    id: 138,
    name: "Lampe horticole LED spectre complet",
    category: "Jardinage",
    price: 34, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.cjdropshipping.com",
    image: "img/jard_lampe_horticole.jpg",
    description: "Lampe de croissance LED 45W spectre complet (380-780nm). Couvre 60×60cm. Efficacité 2,7 µmol/J. Ideal semis, bouturage, culture indoor toute l'année. Durée de vie 50 000h. Consomme 5× moins qu'une lampe sodium.",
    badges: ["Nouveau"],
    rating: 4.7,
    reviews: 0,
    shipping: "Livraison 5-7 jours",
    variants: [
      { label: "45W — 60×60cm", price: 34, stripeLink: "https://buy.stripe.com/14A28jaj1fwBanx9E2cfN12" },
      { label: "100W — 90×90cm", price: 59, stripeLink: "https://buy.stripe.com/14A7sDaj198d1R1bMacfN13" },
      { label: "200W — 120×120cm", price: 99, stripeLink: "https://buy.stripe.com/28E28jbn5gAF3Z93fEcfN14" }
    ],
  },
  {
    id: 139,
    name: "Engrais bio guano de chauve-souris 1L",
    category: "Jardinage",
    price: 14, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/jard_engrais_guano.jpg",
    description: "Engrais biologique liquide à base de guano de chauve-souris. Riche en NPK naturel (7-3-1). Stimule la croissance, améliore la résistance aux maladies. 1L concentré = 100L de solution. Compatible agriculture biologique — certification AB.",
    badges: ["Nouveau","Bio"],
    rating: 4.5,
    reviews: 0,
    shipping: "Livraison 2-3 jours",
    variants: [
      { label: "1L — Croissance (N fort)", price: 14, stripeLink: "https://buy.stripe.com/7sYeV54YH4RXanx8zYcfN15" },
      { label: "1L — Floraison (P fort)", price: 14, stripeLink: "https://buy.stripe.com/9B67sDaj1esx1R19E2cfN16" },
      { label: "5L — Croissance (économique)", price: 55, stripeLink: "https://buy.stripe.com/fZu7sD2Qz7058fpbMacfN17" }
    ],
  },
  {
    id: 140,
    name: "Testeur pH et humidité sol numérique",
    category: "Jardinage",
    price: 19, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.cjdropshipping.com",
    image: "img/jard_testeur_ph.jpg",
    description: "Testeur de sol numérique 3-en-1 : pH (3,5-9), humidité (10-80%), luminosité (0-2000 lux). Sans batterie pour pH/humidité. Sonde acier inox 20cm. Résultats en 60 secondes. Indispensable pour optimiser les cultures et éviter carences.",
    badges: ["Nouveau"],
    rating: 4.5,
    reviews: 0,
    shipping: "Livraison 2-3 jours",
    variants: [
      { label: "3-en-1 — pH + Humidité + Lumière", price: 19, stripeLink: "https://buy.stripe.com/fZudR1gHpbgl0MX4jIcfN18" },
      { label: "Digital LCD — pH seul haute précision", price: 24, stripeLink: "https://buy.stripe.com/00wdR11Mv1FL67heYmcfN19" }
    ],
  },
  {
    id: 141,
    name: "Désherbeur thermique à gaz 2000W",
    category: "Jardinage",
    price: 39, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/jard_desherbeur_gaz.jpg",
    description: "Désherbeur thermique à gaz butane/propane 2000W. Lance-flamme orientable 360°, allumage piézo-électrique. Manche télescopique 85-105cm. Sans herbicide, écologique. Détruit les mauvaises herbes en 2-3 secondes. Compatible cartouches 220g standard.",
    badges: ["Nouveau"],
    rating: 4.4,
    reviews: 0,
    shipping: "Livraison 3-5 jours",
    variants: [
      { label: "2000W — manche télescopique seul", price: 39, stripeLink: "https://buy.stripe.com/00w00b0Ir4RX2V5aI6cfN1a" },
      { label: "2000W — kit complet + 3 cartouches", price: 52, stripeLink: "https://buy.stripe.com/28E00b1Mv5W1dzJ6rQcfN1b" }
    ],
  },
  {
    id: 142,
    name: "Couvercles conservation sous vide — lot de 8",
    category: "Jardinage",
    price: 12, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.cjdropshipping.com",
    image: "img/jard_couvercles_vide.jpg",
    description: "Set de 8 couvercles de conservation sous vide pour bocaux à large ouverture (86mm). Compatibles bocaux Le Parfait, Mason Jar, Ball. Extension jusqu'à 5× la durée de conservation. Pompe manuelle incluse. Sans BPA, réutilisables.",
    badges: ["Nouveau"],
    rating: 4.5,
    reviews: 0,
    shipping: "Livraison 2-3 jours",
    variants: [
      { label: "×8 — 86mm (large) + pompe", price: 12, stripeLink: "https://buy.stripe.com/4gMbIT62L5W1dzJcQecfN1c" },
      { label: "×8 — 70mm (standard) + pompe", price: 12, stripeLink: "https://buy.stripe.com/aFadR1bn5bgl8fp5nMcfN1d" },
      { label: "×16 — mix 70mm + 86mm + pompe électrique", price: 30, stripeLink: "https://buy.stripe.com/fZu9AL0Ir3NTfHRg2qcfN1e" }
    ],
  },
  {
    id: 143,
    name: "Agenouilloir pliable 2-en-1 jardinier",
    category: "Jardinage",
    price: 22, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/jard_agenouilloir.jpg",
    description: "Agenouilloir/tabouret 2-en-1 : retourné devient assise. Mousse EPE 5cm anti-fatigue, structure acier tubulaire Ø25mm, charge max 120 kg. Poids : 1,1 kg. Pliable en 5 secondes. Poignées latérales facilitent les relevés. Idéal arthrose et jardinage prolongé.",
    badges: ["Nouveau"],
    rating: 4.5,
    reviews: 0,
    shipping: "Livraison 3-5 jours",
    variants: [
      { label: "Standard — mousse verte", price: 22, stripeLink: "https://buy.stripe.com/dRm3cn8aTfwB67hbMacfN1f" },
      { label: "Large — mousse grise + poches outils", price: 30, stripeLink: "https://buy.stripe.com/14A3cn1MvachdzJ4jIcfN1g" }
    ],
  },
  {
    id: 144,
    name: "Grelinette bio 3 dents",
    category: "Jardinage",
    price: 38, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/grelinette.jpg",
    description: "Grelinette bio 3 dents en acier forgé, manche hêtre 120cm. Ameublit sans retourner, préserve vers et vie du sol. L'outil bio par excellence.",
    badges: ["Nouveau","Bio"],
    rating: 4.8,
    reviews: 0,
    shipping: "Livraison 5-7 jours",
    variants: [
      { label: "3 dents — manche hêtre 120cm", price: 38, stripeLink: "https://buy.stripe.com/3cIdR1fDl0BH9jt17wcfN1h" },
      { label: "5 dents — manche hêtre 130cm", price: 52, stripeLink: "https://buy.stripe.com/dRm5kvaj15W1cvFcQecfN1i" }
    ],
  },
  {
    id: 145,
    name: "Couteau désherbeur en acier inox",
    category: "Jardinage",
    price: 12, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/couteau_desherbage.jpg",
    description: "Couteau désherbeur lame acier inox 18cm. Tranche les racines au ras du sol sans les arracher. Poignée ergonomique. Idéal allées, bordures, potager.",
    badges: ["Nouveau"],
    rating: 4.5,
    reviews: 0,
    shipping: "Livraison 2-3 jours",
    variants: [
      { label: "Couteau désherbeur 18cm", price: 12, stripeLink: "https://buy.stripe.com/3cI7sD8aTdot0MX9E2cfN1j" }
    ],
  },
  {
    id: 146,
    name: "Système hydroponique 12 sites DWC",
    category: "Jardinage",
    price: 35, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.cjdropshipping.com",
    image: "img/hydro_dwc.jpg",
    description: "Système hydroponique DWC 12 sites. Bac 30L, pompe à air, pierre diffusante, 12 godets + filets. Culture laitues, herbes, fraises. 3× plus rapide qu'en terre.",
    badges: ["Nouveau"],
    rating: 4.6,
    reviews: 0,
    shipping: "Livraison 5-7 jours",
    variants: [
      { label: "12 sites — bac 30L", price: 35, stripeLink: "https://buy.stripe.com/7sYaEP62L705gLV6rQcfN1k" },
      { label: "24 sites — bac 60L", price: 59, stripeLink: "https://buy.stripe.com/8x2fZ94YH705gLVbMacfN1l" }
    ],
  },
  {
    id: 147,
    name: "Thermohygromètre digital pour serre",
    category: "Jardinage",
    price: 14, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.cjdropshipping.com",
    image: "img/thermohygrometre.jpg",
    description: "Thermohygromètre digital pour serre et culture indoor. Plage -50°C à +70°C, humidité 10-99%. Mémoire min/max, icône confort. Écran LCD rétroéclairé.",
    badges: ["Nouveau"],
    rating: 4.5,
    reviews: 0,
    shipping: "Livraison 2-3 jours",
    variants: [
      { label: "Digital LCD — température + humidité", price: 14, stripeLink: "https://buy.stripe.com/6oU4grdvd7059jt8zYcfN1m" },
      { label: "WiFi — app smartphone", price: 22, stripeLink: "https://buy.stripe.com/eVq6ozezhachcvFcQecfN1n" }
    ],
  },
  {
    id: 149,
    name: "Minuterie électrique 7 jours programmable",
    category: "Jardinage",
    price: 9, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.cjdropshipping.com",
    image: "img/minuterie_16a.jpg",
    description: "Minuterie électrique programmable 7 jours 16A. Pour lampe horticole, pompe hydroponique, chauffage serre. 20 programmes par jour. LCD, charge max 3680W.",
    badges: ["Nouveau"],
    rating: 4.5,
    reviews: 0,
    shipping: "Livraison 2-3 jours",
    variants: [
      { label: "Minuterie 16A — 20 programmes", price: 9, stripeLink: "https://buy.stripe.com/9B6eV54YHckpgLV03scfN1q" }
    ],
  },
  {
    id: 150,
    name: "Substrat coco/coir culture premium 50L",
    category: "Jardinage",
    price: 18, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/substrat_coco.jpg",
    description: "Substrat de culture coco/coir premium 50L. Lavé et tamponné pH 5,8-6,2. Utilisable seul, en mélange sol ou hydroponique. Certifié OMRI bio. Excellent drainage et rétention.",
    badges: ["Nouveau","Bio"],
    rating: 4.5,
    reviews: 0,
    shipping: "Livraison 5-7 jours",
    variants: [
      { label: "50L — bloc compressé", price: 18, stripeLink: "https://buy.stripe.com/dRmeV5dvd5W1dzJ9E2cfN1r" },
      { label: "100L — lot de 2", price: 34, stripeLink: "https://buy.stripe.com/00waEP2Qz0BHbrB3fEcfN1s" }
    ],
  }
];

// ── Nouveaux produits Survie (IDs 200-207) ─────────────────────────────────
const PRODUCTS_SURVIE_NEW = [
  {
    id: 200,
    name: "Filtre à eau portable LifeStraw 1000L",
    category: "Survie",
    price: 19, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.cjdropshipping.com",
    image: "img/surv_lifestraw.jpg",
    description: "Filtre à eau LifeStraw certifié. Élimine 99,9999% des bactéries (E.coli, Salmonella) et 99,9% des parasites (Giardia, Cryptosporidium). Capacité 1000 litres — zéro produit chimique, zéro pile. Poids 56g. Boire directement dans rivières et sources. Le filtre de survie le plus vendu au monde.",
    badges: ["Nouveau","Essentiel"],
    rating: 4.9,
    reviews: 0,
    shipping: "Livraison 2-3 jours",
    variants: [
      { label: "Filtre paille 1000L — bleu", price: 19, stripeLink: "https://buy.stripe.com/fZuaEPezh2JP1R1bMacfN1t" },
      { label: "Filtre paille 1000L — vert", price: 19, stripeLink: "https://buy.stripe.com/5kQ14f62LfwB67hdUicfN1u" },
      { label: "Bouteille filtrante 650mL + filtre 4000L", price: 29, stripeLink: "https://buy.stripe.com/eVqfZ90Ir5W167haI6cfN1v" }
    ],
  },
  {
    id: 201,
    name: "Batterie solaire 20000mAh panneau 5W",
    category: "Énergie",
    price: 34, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.cjdropshipping.com",
    image: "img/surv_batterie_solaire.jpg",
    description: "Power bank solaire 20000mAh avec panneau 5W intégré. 2 sorties USB-A (5V/2.1A) + 1 USB-C (5V/3A). Rechargeable par soleil en 15-20h ou secteur en 8h. Indicateur LED, imperméable IPX5. Charge smartphone jusqu'à 5× ou tablette 2×. Parfait camping, randonnée, panne de courant.",
    badges: ["Nouveau","Essentiel"],
    rating: 4.7,
    reviews: 0,
    shipping: "Livraison 5-7 jours",
    variants: [
      { label: "20000mAh — noir", price: 34, stripeLink: "https://buy.stripe.com/3cIbITfDl3NT53d8zYcfN1w" },
      { label: "20000mAh — vert kaki", price: 34, stripeLink: "https://buy.stripe.com/cNi5kv62L4RX53daI6cfN1x" },
      { label: "40000mAh — double panneau 10W", price: 59, stripeLink: "https://buy.stripe.com/cNicMX4YHdot9jt5nMcfN1y" }
    ],
  },
  {
    id: 202,
    name: "Trousse premiers secours 42 pièces",
    category: "Survie",
    price: 18, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/surv_trousse_secours.jpg",
    description: "Kit premiers secours complet 42 pièces en pochette imperméable nylon. Inclus : pansements (18 tailles), compresses stériles, bandes élastiques, ciseaux, épingles de sûreté, gants nitrile, masque RCP, garrot, couverture survie. Conforme EN 13157. Idéal randonnée, voiture, bivouac.",
    badges: ["Nouveau","Essentiel"],
    rating: 4.7,
    reviews: 0,
    shipping: "Livraison 2-3 jours",
    variants: [
      { label: "42 pièces — pochette nylon", price: 18, stripeLink: "https://buy.stripe.com/cNi4grfDlfwB0MXg2qcfN1z" },
      { label: "72 pièces — mallette rigide", price: 30 },
      { label: "Kit auto — norme DIN13164", price: 22, stripeLink: "https://buy.stripe.com/dRm28jfDlfwBanxcQecfN1B" }
    ],
  },
  {
    id: 203,
    name: "Kit allume-feu survie 3-en-1",
    category: "Survie",
    price: 14, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.cjdropshipping.com",
    image: "img/surv_kit_feu.jpg",
    description: "Kit allume-feu de survie 3-en-1 : briquet tempête rechargeable USB résistant vent jusqu'à 80 km/h + pierre à feu ferrocerium 12cm (12 000 frappes) + bâtonnet d'amadou. Étui imperméable inclus. Fonctionne sous la pluie, à -20°C, à toute altitude. Le trio indispensable du kit 72h.",
    badges: ["Nouveau"],
    rating: 4.6,
    reviews: 0,
    shipping: "Livraison 2-3 jours",
    variants: [
      { label: "Kit 3-en-1 — étui noir", price: 14, stripeLink: "https://buy.stripe.com/4gM4grgHp3NT2V517wcfN1C" },
      { label: "Kit 3-en-1 — étui kaki", price: 14, stripeLink: "https://buy.stripe.com/00w28jcr91FL1R16rQcfN1D" },
      { label: "Kit étendu — + allume-feu magnésium + sifflet", price: 19, stripeLink: "https://buy.stripe.com/28EfZ98aTfwBbrB17wcfN1E" }
    ],
  },
  {
    id: 204,
    name: "Couvertures survie mylar — lot de 4",
    category: "Survie",
    price: 9, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.bigbuy.eu/fr",
    image: "img/surv_couverture_mylar.jpg",
    description: "Couvertures de survie mylar 160×210cm. Réfléchissent 90% de la chaleur corporelle. Film aluminium double face (or/argent). Imperméables, légères (50g chacune), format poche. Certifiées CE. Protègent aussi contre le soleil et le vent. Lot de 4 — pour toute la famille.",
    badges: ["Nouveau","Essentiel"],
    rating: 4.6,
    reviews: 0,
    shipping: "Livraison 2-3 jours",
    variants: [
      { label: "×4 — 160×210cm or/argent", price: 9, stripeLink: "https://buy.stripe.com/fZu5kv2Qz0BHanxg2qcfN1F" },
      { label: "×10 — format lot économique", price: 19, stripeLink: "https://buy.stripe.com/8x2aEPdvdckp7bl9E2cfN1G" },
      { label: "Sac de couchage mylar réutilisable", price: 22, stripeLink: "https://buy.stripe.com/dRmeV562L2JP0MX03scfN1H" }
    ],
  },
  {
    id: 205,
    name: "Radio météo manivelle solaire DAB+/FM",
    category: "Électronique outdoor",
    price: 39, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.cjdropshipping.com",
    image: "img/surv_radio_manivelle.jpg",
    description: "Radio d'urgence multi-énergie DAB+/FM/AM/SW. 4 modes d'alimentation : manivelle dynamo (1 min → 20 min autonomie), panneau solaire, batterie intégrée 2000mAh, micro-USB. Lampe LED 3W. Alerte météo NOAA. Imperméable IPX3. Fonctionne sans électricité ni réseau.",
    badges: ["Nouveau"],
    rating: 4.5,
    reviews: 0,
    shipping: "Livraison 5-7 jours",
    variants: [
      { label: "DAB+/FM/AM — vert kaki", price: 39, stripeLink: "https://buy.stripe.com/fZubITcr998d67h7vUcfN1I" },
      { label: "DAB+/FM/AM — orange", price: 39, stripeLink: "https://buy.stripe.com/cNi4graj1dot9jt2bAcfN1J" },
      { label: "Version Pro — batterie 5000mAh + BT", price: 59, stripeLink: "https://buy.stripe.com/4gMcMX1Mv5W10MXg2qcfN1K" }
    ],
  },
  {
    id: 206,
    name: "Sac de couchage compact 0°C / -5°C",
    category: "Survie",
    price: 44, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.cjdropshipping.com",
    image: "img/surv_sac_couchage.jpg",
    description: "Sac de couchage 3 saisons coupe momie. Garnissage fibre creuse thermique 250g/m². Fermeture éclair YKK double sens anti-accrochage. Compression 3,8L, poids 900g. Température confort 0°C / limite -5°C. Doublure polyester doux. Idéal bivouac, camping, kit d'urgence.",
    badges: ["Nouveau"],
    rating: 4.5,
    reviews: 0,
    shipping: "Livraison 5-7 jours",
    variants: [
      { label: "Confort 0°C — bleu — 900g", price: 44, stripeLink: "https://buy.stripe.com/7sYdR1cr9esx2V58zYcfN1L" },
      { label: "Confort 0°C — vert kaki — 900g", price: 44, stripeLink: "https://buy.stripe.com/3cI00bcr9ach0MXcQecfN1M" },
      { label: "Confort -10°C — hiver — 1100g", price: 64, stripeLink: "https://buy.stripe.com/4gM3cn3UDgAFcvFg2qcfN1N" }
    ],
  },
  {
    id: 207,
    name: "Corde paracorde 550 — 30m + kit survie",
    category: "Survie",
    price: 14, 
    supplier: "CJdropshipping",
    supplierUrl: "https://www.cjdropshipping.com",
    image: "img/surv_paracorde.jpg",
    description: "Corde paracorde militaire MIL-C-5040H type III — résistance 250kg (550 lbs). 30 mètres. Gaine nylon 32 fuseaux, 7 brins intérieurs réutilisables (ligature, suture urgence, fabrication filet). Kit survie inclus : briquet, sifflet 120dB, boussole, grattoir ferro. Coloris olive/noir/camo.",
    badges: ["Nouveau"],
    rating: 4.6,
    reviews: 0,
    shipping: "Livraison 2-3 jours",
    variants: [
      { label: "30m — Olive + kit survie 4-en-1", price: 14, stripeLink: "https://buy.stripe.com/cNieV53UDckpanxaI6cfN1O" },
      { label: "30m — Noir + kit survie 4-en-1", price: 14, stripeLink: "https://buy.stripe.com/fZudR176P7059jtdUicfN1P" },
      { label: "30m — Camo + kit survie 4-en-1", price: 14, stripeLink: "https://buy.stripe.com/3cI6oz8aT2JPdzJ6rQcfN1Q" },
      { label: "100m — bobine pro olive", price: 34, stripeLink: "https://buy.stripe.com/5kQeV5aj11FLgLVcQecfN1R" }
    ],
  }
];
// Fusionner tous les produits
const ALL_PRODUCTS = [...PRODUCTS, ...PRODUCTS_JARDINAGE, ...PRODUCTS_SURVIE_NEW];
// Catégories disponibles
const CATEGORIES = [
  { id: "all", name: "Tous les produits", emoji: "🏷️", count: 63 },
  { id: "Survie", name: "Survie", emoji: "🏕️", count: 13 },
  { id: "Éclairage", name: "Éclairage", emoji: "🔦", count: 6 },
  { id: "Alimentation outdoor", name: "Alimentation outdoor", emoji: "🥾", count: 6 },
  { id: "Montres outdoor", name: "Montres outdoor", emoji: "⌚", count: 2 },
  { id: "Sacs à dos", name: "Sacs à dos", emoji: "🎒", count: 4 },
  { id: "Pêche", name: "Pêche", emoji: "🎣", count: 2 },
  { id: "Énergie", name: "Énergie", emoji: "⚡", count: 4 },
  { id: "Électronique outdoor", name: "Électronique outdoor", emoji: "📡", count: 5 },
  { id: "Escalade", name: "Escalade", emoji: "🧗", count: 3 },
  { id: "Cyclisme & Trail", name: "Cyclisme & Trail", emoji: "🚵", count: 3 },
  { id: "Vêtements outdoor", name: "Vêtements outdoor", emoji: "🧥", count: 1 },
  { id: "Outils", name: "Outils", emoji: "🔪", count: 8 },
  { id: "Jardinage", name: "Jardinage", emoji: "🌱", count: 30 }
];

// Couleurs des badges
const BADGE_COLORS = {
  "Bio": { bg: "#e8f5e9", color: "#2e7d32", emoji: "🌿" },
  "Bestseller": { bg: "#fce4ec", color: "#c62828", emoji: "⭐" },
  "Nouveau": { bg: "#e3f2fd", color: "#1565c0", emoji: "✨" },
  "Essentiel": { bg: "#f3e5f5", color: "#6a1b9a", emoji: "💎" },
  "Survie": { bg: "#e8f5e9", color: "#1b5e20", emoji: "🏕️" }
};

// Fonctions utilitaires produits
function getProductById(id) {
  return ALL_PRODUCTS.find(p => p.id === parseInt(id));
}

function getProductsByCategory(category) {
  if (category === "all") return ALL_PRODUCTS;
  return ALL_PRODUCTS.filter(p => p.category === category);
}

function getFeaturedProducts() {
  return PRODUCTS.filter(p => Array.isArray(p.badges) && p.badges.includes("Bestseller")).slice(0, 4);
}

function getNewProducts() {
  return PRODUCTS.filter(p => Array.isArray(p.badges) && p.badges.includes("Nouveau"));
}

function getPromoProducts() {
  return PRODUCTS.filter(p => Array.isArray(p.badges) && p.badges.includes("Promo"));
}

function searchProducts(query) {
  const q = query.toLowerCase();
  return PRODUCTS.filter(p =>
    p.name.toLowerCase().includes(q) ||
    p.description.toLowerCase().includes(q) ||
    p.category.toLowerCase().includes(q)
  );
}

function sortProducts(products, sortBy) {
  const sorted = [...products];
  switch (sortBy) {
    case "price-asc":
      return sorted.sort((a, b) => a.price - b.price);
    case "price-desc":
      return sorted.sort((a, b) => b.price - a.price);
    case "rating":
      return sorted.sort((a, b) => b.rating - a.rating);
    case "reviews":
      return sorted.sort((a, b) => b.reviews - a.reviews);
    case "name":
      return sorted.sort((a, b) => a.name.localeCompare(b.name, 'fr'));
    default:
      return sorted;
  }
}

function formatPrice(price) {
  return price.toFixed(2).replace('.', ',') + ' €';
}

function getDiscountPercent(price, originalPrice) {
  return Math.round((1 - price / originalPrice) * 100);
}

function renderStars(rating) {
  const full = Math.floor(rating);
  const half = rating % 1 >= 0.5 ? 1 : 0;
  const empty = 5 - full - half;
  return '★'.repeat(full) + (half ? '½' : '') + '☆'.repeat(empty);
}

function renderBadges(badges) {
  if (!Array.isArray(badges) || badges.length === 0) return '';
  return badges.map(badge => {
    const config = BADGE_COLORS[badge];
    if (!config) return '';
    return `<span class="badge" style="background:${config.bg};color:${config.color}">${config.emoji} ${badge}</span>`;
  }).join('');
}

function renderSupplier(product) {
  if (!product.supplier) return '';
  return `<div class="product-supplier" title="Fournisseur : ${product.supplier}">
    🏭 <span>${product.supplier}</span>
  </div>`;
}

function renderProductCard(product) {
  const discount = product.originalPrice
    ? Math.round((1 - product.price / product.originalPrice) * 100)
    : 0;
  const badge = (product.badges && product.badges[0]) ? product.badges[0] : product.category;
  return `
    <div class="jard-card" onclick="window.location='produit.html?id=${product.id}'" style="cursor:pointer">
      <img class="jard-card-img" src="${product.image}" alt="${product.name}" loading="lazy">
      <div class="jard-card-body">
        <span class="jard-cat-badge">🎒 ${badge}</span>
        <h3 class="jard-card-title">${product.name}</h3>
        <p class="jard-card-desc">${product.description ? product.description.substring(0, 90) + (product.description.length > 90 ? '…' : '') : ''}</p>
        <div style="color:#f59e0b;font-size:0.82rem;margin-bottom:8px;">${renderStars(product.rating)} <span style="color:#888;font-size:0.78rem;">(${product.reviews})</span></div>
        <div class="jard-card-footer">
          <div>
            <span class="jard-price">${formatPrice(product.price)}</span>
            ${product.originalPrice ? `<span style="font-size:0.8rem;color:#999;text-decoration:line-through;margin-left:6px;">${formatPrice(product.originalPrice)}</span>` : ''}
            ${discount > 0 ? `<span style="background:#c0392b;color:#fff;font-size:0.72rem;font-weight:700;padding:2px 7px;border-radius:10px;margin-left:6px;">-${discount}%</span>` : ''}
          </div>
          <button onclick="event.stopPropagation();Cart.add(${product.id})" class="jard-btn" type="button">🛒 Ajouter au panier</button>
        </div>
      </div>
    </div>
  `;
}


